#!/usr/bin/env python3
# This python script combines each leg in the "lege" subfolder into a json list in
# a javascript file "lege.js"

import glob
import os

def strn(s):
    s = s.replace('"', r'\"')
    return '"'+s+'"'

def sort_key(s):
    d = {"name": 0,
         "teaser": 1,
         "inside": 2,
         "youtube": 3,
         "tags": 4,
         "min_age": 5,
         "max_age": 6,
         "min_time": 7,
         "max_time": 8,
         "min_participants": 9,
         "max_participants": 10,
         "description": 11}
    key = d.get(s, 1000)
    return (key, s)

def build_lege():
    filenames = glob.glob("lege/*.leg")
    filenames.sort()

    lege = []
    for filename in filenames:
        with open(filename) as file:
            leg = {}
            while True:
                line = file.readline()
                if line == "":
                    break
                items = [item.strip() for item in line.split(":", 1)]

                if len(items) == 1:
                    key = items[0].lower()
                    value = "null"
                elif len(items) == 2:
                    key = items[0].lower()
                    value = items[1]
                else:
                    raise Exception("Could not split on :")

                if key == "description":
                    leg[key] = value + file.read()
                    break
                leg[key] = value

            if "name" not in leg:
                raise Exception("Leg has no name")

            for key, value in leg.items():
                if value.isnumeric() or key == "inside":
                    leg[key] = value
                elif key == "youtube":
                    leg[key] = "null" if value == "" else strn(value)
                elif key == "tags":
                    taglist = (strn(tag.strip()) for tag in value.split(","))
                    tags = "[" + ", ".join(taglist) + "]"
                    leg[key] = tags
                else:
                    leg[key] = strn(value)
            lege.append(leg)

    js_list = []
    for leg in lege:
        js_object = []
        for key in sorted(leg.keys(), key=sort_key):
            js_object.append("    " + key + ": " + leg[key])
        js_list.append("  {\n" + ",\n".join(js_object) + "\n  }")
        content = "lege = [\n" + ",\n".join(js_list) + "\n];\n"
    with open("lege.js_", "w") as js:
        js.write("# DO NOT EDIT THIS FILE!!!\n")
        js.write("# This file is created automatically by build.py\n")
        js.write("# Any manual changes here WILL be forgotten\n\n\n\n")

        js.write(content)

    os.system("mv lege.js_ lege.js")

if __name__ == "__main__":
    build_lege()
